dist: trusty
language: java
jdk:
  - oraclejdk8
sudo: true
script: mvn clean verify
after_success:
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
